version: "3.9"

services:
    backend:
        build: ./backend
        container_name:  backend
        restart: always
        environment: 
            - SECRET_KEY='cd48e1c22de0961d5d1bfb14f8a66e006cfb1cfbf3f0c0f3'
            - MONGODB_USER=table_app
            - MONGODB_PASSWORD=gjhtqqw3124t
        expose:
            - 5000
        depends_on:
            - mongodb

    frontend:
        build: ./frontend
        container_name:  frontend
        tty: true
        restart: always
        ports:
            - "80:80"
        expose:
            - 8080

    mongodb:
        build: ./database
        container_name:  mongodb
        restart: always
        volumes:
            - './database:/db'
        ports:
            - "27017:27017"
            - "27018:27018"
            - "27019:27019"
        expose:
            - 27017
            - 27018
            - 27019

    mongo-express:
        image: mongo-express
        restart: always
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin-user
            - ME_CONFIG_MONGODB_ADMINPASSWORD=admin-password
            - ME_CONFIG_MONGODB_SERVER=mongodb
            - ME_CONFIG_MONGODB_PORT=27017
            # web login username and password
            - ME_CONFIG_BASICAUTH_USERNAME=admin-user
            - ME_CONFIG_BASICAUTH_PASSWORD=admin-password
        ports:
            - 8081:8081
        depends_on:
            - mongodb
